#%%

### https://finnhub.io/docs/api
### https://github.com/Finnhub-Stock-API/finnhub-python
### https://github.com/vertica/vertica-python
# pip3 install finnhub-python vertica-python verticapy maya

# https://www.alphavantage.co/support/#api-key

# O0LDS7A14EH1HDNP
# https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=PETR4.SA&apikey=O0LDS7A14EH1HDNP

#https://tradingeconomics.com/brazil/stock-market

import time
import maya
import requests
import datetime
import vertica_python
from finnhub import Client

def connectVertica():
    conn_info = {'host': '127.0.0.1',
                'port': 5433,
                'user': 'dbadmin',
                'password': 'stocks',
                'database': 'stocks',
                # autogenerated session label by default,
                #'session_label': 'some_label',
                # default throw error on invalid UTF-8 results
                'unicode_error': 'strict',
                # SSL is disabled by default
                'ssl': False,
                # using server-side prepared statements is disabled by default
                'use_prepared_statements': True,
                # connection timeout is not enabled by default
                # 5 seconds timeout for a socket operation (Establishing a TCP connection or read/write operation)
                'connection_timeout': 3600}

    # simple connection, with manual close
    return vertica_python.connect(**conn_info)

# https://www.alphavantage.co/documentation/

# https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=CVCB3.SA&apikey=O0LDS7A14EH1HDNP
# https://www.alphavantage.co/query?function=FX_INTRADAY&from_symbol=EUR&to_symbol=BRL&interval=5min&apikey=O0LDS7A14EH1HDNP

# https://www.alphavantage.co/query?function=DEMA&symbol=CVCB3.SA&interval=daily&time_period=10&series_type=open&apikey=O0LDS7A14EH1HDNP
# https://www.alphavantage.co/query?function=TEMA&symbol=CVCB3.SA&interval=daily&time_period=10&series_type=open&apikey=O0LDS7A14EH1HDNP
# https://www.alphavantage.co/query?function=TRIMA&symbol=CVCB3.SA&interval=daily&time_period=10&series_type=open&apikey=O0LDS7A14EH1HDNP


def query_symbol_data(symbol, function="TIME_SERIES_DAILY", compact=True):
        outputsize = "compact"
        if not compact: outputsize = "full"
        url = f"https://www.alphavantage.co/query?function={function}&apikey=O0LDS7A14EH1HDNP&outputsize={outputsize}&symbol={symbol}"
        response = requests.request('GET', url)
        try:
            return response.json()
        except Exception as error:
           print(f"{response} - {str(error)}")

def getDbLastTimestamp(symbol, table_name="daily_prices", column_name="ts"):
    return cur.execute(f"SELECT MAX(\"{column_name}\") as \"{column_name}\" FROM {table_name} WHERE symbol = '{symbol}';").fetchone()[0]

def load_symbol_daily_data(symbol):
    print(f"loading symbol data: {symbol}")
    cur.execute("CREATE TABLE IF NOT EXISTS daily_prices (ts DATETIME, symbol VARCHAR(15), open NUMERIC(12,4), high NUMERIC(12,4), low NUMERIC(12,4), close NUMERIC(12,4), volume NUMERIC(18) )")
    resp = query_symbol_data(symbol, "TIME_SERIES_DAILY", True)
    db_last_ts = getDbLastTimestamp(symbol)
    print(f"db_last_ts: {db_last_ts}")
    buffer = []
    for ts in resp["Time Series (Daily)"]:
        ts_obj = maya.parse(ts).datetime()
        if ts_obj.date() > db_last_ts.date():
            print(f"New Data found: {ts_obj}")
            data = resp["Time Series (Daily)"][ts]
            buffer.append( (ts, resp["Meta Data"]["2. Symbol"], data['1. open'], data['2. high'], data['3. low'], data['4. close'], data['5. volume'])  )
            if len(buffer) == 1000:
                print(len(buffer))
                cur.executemany("INSERT INTO daily_prices VALUES (?, ?, ?, ?, ?, ?, ?);", buffer)
                buffer.clear()
                time.sleep(3)
    if len(buffer) > 0:
        cur.executemany("INSERT INTO daily_prices VALUES (?, ?, ?, ?, ?, ?, ?);", buffer)
    cur.execute("select do_tm_task('mergeout', 'daily_prices');")
    cur.execute("COMMIT;")
    print(f"daily_prices loaded for symbol {symbol}")


symbols = [ 'ABEV3.SA',
            'B3SA3.SA',
            'BBAS3.SA',
            'BBDC4.SA',
            'BBSE3.SA',
            'BOVA11.SA',
            'BRFS3.SA',
            'BRKM5.SA',
            'BRML3.SA',
            'CCRO3.SA',
            'CIEL3.SA',
            'CMIG4.SA',
            'COGN3.SA',
            'CSAN3.SA',
            'CSNA3.SA',
            'CYRE3.SA',
            'ECOR3.SA',
            'EGIE3.SA',
            'ELET3.SA',
            'EMBR3.SA',
            'EQTL3.SA',
            'GGBR4.SA',
            'GOAU4.SA',
            'HYPE3.SA',
            'IRBR3.SA',
            'ITSA4.SA',
            'ITUB4.SA',
            'JBSS3.SA',
            'LAME4.SA',
            'LREN3.SA',
            'MGLU3.SA',
            'MRFG3.SA',
            'NTCO3.SA',
            'CVCB3.SA',
            'PETR4.SA',
            'QUAL3.SA',
            'RADL3.SA',
            'RAIL3.SA',
            'RENT3.SA',
            'SBSP3.SA',
            'SUZB3.SA',
            'TAEE11.SA',
            'USIM5.SA',
            'VALE3.SA',
            'VIVT4.SA',
            'VVAR3.SA',
            'WEGE3.SA',
            'YDUQ3.SA']

# using with for auto connection closing after usage
with connectVertica() as connection:
    cur = connection.cursor()
    #cur.execute("TRUNCATE TABLE daily_prices;")
    #cur.execute("COMMIT;")
    for symbol in symbols:
        load_symbol_daily_data(symbol)
        time.sleep(30)

        
    
    
    
    
#cur.execute("CREATE TABLE IF NOT EXISTS stock_symbols (currency VARCHAR(10), description VARCHAR(255), displaySymbol VARCHAR(128), type VARCHAR(10) )")
#cur.execute("TRUNCATE TABLE stock_symbols")
#print(finnhub_client.exchange())
'''
buffer = []
for symbol in finnhub_client.stock_symbols('BR'):
    buffer.append( ( symbol['currency'], symbol['description'], symbol['displaySymbol'], symbol['type'])  )
    if len(buffer) == 500:
        print(len(buffer))
        cur.executemany("INSERT INTO stock_symbols VALUES (?, ?, ?, ?);", buffer)
        cur.execute("select do_tm_task('mergeout', 'stock_symbols');")
        buffer.clear()
if len(buffer) > 0:
    cur.executemany("INSERT INTO stock_symbols VALUES (?, ?, ?, ?);", buffer)
cur.execute("COMMIT")
print("stock_symbols loaded")
'''
    
# Setup client
#finnhub_client = Client(api_key="bqu00jvrh5rb3gqqf9q0")

#print(finnhub_client.quote("PETR4.SA"))

#print(finnhub_client.stock_symbols('BR')[0:5])

# Stock candles
#res = finnhub_client.stock_candles('AAPL', 'D', 1590988249, 1591852249)
#print(res)

# News sentiment
#print(finnhub_client.news_sentiment('AAPL'))





# %%
