create schema stocks 

select * from stocks.stock_symbols;
drop table if exists stocks.stock_symbols;
CREATE TABLE IF NOT EXISTS stocks.stock_symbols (company VARCHAR(50), symbol VARCHAR(10), industry VARCHAR(100), headquarters VARCHAR(100) );
INSERT INTO stocks.stock_symbols VALUES ('AmBev', 'ABEV3', 'beverages', 'São Paulo');
INSERT INTO stocks.stock_symbols VALUES ('Azul', 'AZUL4', 'airlines', 'Barueri');
INSERT INTO stocks.stock_symbols VALUES ('B2W', 'BTOW3', 'online retail', 'Rio de Janeiro');
INSERT INTO stocks.stock_symbols VALUES ('B3', 'B3SA3', 'stock exchange', 'São Paulo');
INSERT INTO stocks.stock_symbols VALUES ('Banco do Brasil', 'BBAS3', 'banking', 'Brasília');
INSERT INTO stocks.stock_symbols VALUES ('BB Seguridade', 'BBSE3', 'insurance', 'Brasília');
INSERT INTO stocks.stock_symbols VALUES ('Bradesco', 'BBDC3', 'banking', 'Osasco');
INSERT INTO stocks.stock_symbols VALUES ('Bradesco', 'BBDC4', 'banking', 'Osasco');
INSERT INTO stocks.stock_symbols VALUES ('Bradespar', 'BRAP4', 'holding', 'São Paulo');
INSERT INTO stocks.stock_symbols VALUES ('BRMalls', 'BRML3', 'real state', 'Rio de Janeiro');
INSERT INTO stocks.stock_symbols VALUES ('Braskem', 'BRKM5', 'petrochemicals', 'São Paulo');
INSERT INTO stocks.stock_symbols VALUES ('BRF', 'BRFS3', 'foods', 'Itajaí');
INSERT INTO stocks.stock_symbols VALUES ('BTG Pactual', 'BPAC11', 'banking', 'São Paulo');
INSERT INTO stocks.stock_symbols VALUES ('Carrefour Brasil', 'CRFB3', 'retail', 'São Paulo');
INSERT INTO stocks.stock_symbols VALUES ('CCR', 'CCRO3', 'transportation', 'São Paulo');
INSERT INTO stocks.stock_symbols VALUES ('CVC Brasil', 'CVCB3', 'travel and tourism', 'Santo André');
INSERT INTO stocks.stock_symbols VALUES ('CEMIG', 'CMIG4', 'electricity utility', 'Belo Horizonte');
INSERT INTO stocks.stock_symbols VALUES ('Cia. Hering', 'HGTX3', 'clothing', 'Blumenau');
INSERT INTO stocks.stock_symbols VALUES ('Cielo', 'CIEL3', 'payment system', 'Barueri');
INSERT INTO stocks.stock_symbols VALUES ('Cogna', 'COGN3', 'higher education', 'Belo Horizonte');
INSERT INTO stocks.stock_symbols VALUES ('Cosan', 'CSAN3', 'conglomerate', 'São Paulo');
INSERT INTO stocks.stock_symbols VALUES ('CPFL Energia', 'CPFE3', 'electric utility', 'Campinas');
INSERT INTO stocks.stock_symbols VALUES ('CSN', 'CSNA3', 'siderurgy and metallurgy', 'Rio de Janeiro');
INSERT INTO stocks.stock_symbols VALUES ('Cyrela Brazil Realty', 'CYRE3', 'real estate', 'São Paulo');
INSERT INTO stocks.stock_symbols VALUES ('EcoRodovias', 'ECOR3', 'transportation', 'São Paulo');
INSERT INTO stocks.stock_symbols VALUES ('EDP - Energias do Brasil', 'ENBR3', 'electricity utility', 'São Paulo');
INSERT INTO stocks.stock_symbols VALUES ('Eletrobras', 'ELET3', 'electric utility', 'Rio de Janeiro');
INSERT INTO stocks.stock_symbols VALUES ('Eletrobras', 'ELET6', 'electric utility', 'Rio de Janeiro');
INSERT INTO stocks.stock_symbols VALUES ('Embraer', 'EMBR3', 'aerospace/defense', 'São José dos Campos');
INSERT INTO stocks.stock_symbols VALUES ('ENGIE Brasil', 'EGIE3', 'electricity utility', 'Florianópolis');
INSERT INTO stocks.stock_symbols VALUES ('Equatorial Energia', 'EQTL3', 'electricity utility', 'Brasília');
INSERT INTO stocks.stock_symbols VALUES ('Gerdau', 'GGBR4', 'siderurgy and metallurgy', 'São Paulo');
INSERT INTO stocks.stock_symbols VALUES ('Gol', 'GOLL4', 'airlines', 'São Paulo');
INSERT INTO stocks.stock_symbols VALUES ('GPA', 'PCAR4', 'retail', 'São Paulo');
INSERT INTO stocks.stock_symbols VALUES ('Grupo Fleury', 'FLRY3', 'healthcare', 'São Paulo');
INSERT INTO stocks.stock_symbols VALUES ('Grupo Hapvida', 'HAPV3', 'healthcare', 'Fortaleza');
INSERT INTO stocks.stock_symbols VALUES ('Hypera Pharma', 'HYPE3', 'pharmaceutical', 'São Paulo');
INSERT INTO stocks.stock_symbols VALUES ('Iguatemi', 'IGTA3', 'shopping malls', 'São Paulo');
INSERT INTO stocks.stock_symbols VALUES ('Intermédica', 'GNDI3', 'healthcare', 'São Paulo');
INSERT INTO stocks.stock_symbols VALUES ('IRB Brasil RE', 'IRBR3', 'insurance', 'Rio de Janeiro');
INSERT INTO stocks.stock_symbols VALUES ('Itaú Unibanco', 'ITUB4', 'banking', 'São Paulo');
INSERT INTO stocks.stock_symbols VALUES ('Itaúsa', 'ITSA4', 'holding', 'São Paulo');
INSERT INTO stocks.stock_symbols VALUES ('JBS', 'JBSS3', 'food and beverages', 'São Paulo');
INSERT INTO stocks.stock_symbols VALUES ('Klabin', 'KLBN11', 'paper and pulp', 'São Paulo');
INSERT INTO stocks.stock_symbols VALUES ('Localiza', 'RENT3', 'rental car', 'Belo Horizonte');
INSERT INTO stocks.stock_symbols VALUES ('Lojas Americanas', 'LAME4', 'department store', 'Rio de Janeiro');
INSERT INTO stocks.stock_symbols VALUES ('Lojas Renner', 'LREN3', 'department store', 'Porto Alegre');
INSERT INTO stocks.stock_symbols VALUES ('Magazine Luiza', 'MGLU3', 'department store', 'São Paulo');
INSERT INTO stocks.stock_symbols VALUES ('Marfrig', 'MRFG3', 'foods', 'São Paulo');
INSERT INTO stocks.stock_symbols VALUES ('Metalúrgica Gerdau', 'GOAU4', 'holding', 'Porto Alegre');
INSERT INTO stocks.stock_symbols VALUES ('Minerva Foods', 'BEEF3', 'foods', 'Barretos');
INSERT INTO stocks.stock_symbols VALUES ('MRV', 'MRVE3', 'construction and real estate', 'Belo Horizonte');
INSERT INTO stocks.stock_symbols VALUES ('Multiplan', 'MULT3', 'shopping malls', 'Rio de Janeiro');
INSERT INTO stocks.stock_symbols VALUES ('Natura & Co', 'NTCO3', 'cosmetics', 'São Paulo');
INSERT INTO stocks.stock_symbols VALUES ('Petrobras', 'PETR3', 'oil and gas', 'Rio de Janeiro');
INSERT INTO stocks.stock_symbols VALUES ('Petrobras', 'PETR4', 'oil and gas', 'Rio de Janeiro');
INSERT INTO stocks.stock_symbols VALUES ('Qualicorp', 'QUAL3', 'insurance', 'São Paulo');
INSERT INTO stocks.stock_symbols VALUES ('RaiaDrogasil', 'RADL3', 'drugstore', 'São Paulo');
INSERT INTO stocks.stock_symbols VALUES ('Rumo', 'RAIL3', 'logistics', 'Curitiba');
INSERT INTO stocks.stock_symbols VALUES ('Sabesp', 'SBSP3', 'waste management', 'São Paulo');
INSERT INTO stocks.stock_symbols VALUES ('Santander Brasil', 'SANB11', 'banking', 'São Paulo');
INSERT INTO stocks.stock_symbols VALUES ('SulAmérica Seguros', 'SULA11', 'insurance', 'Rio de Janeiro');
INSERT INTO stocks.stock_symbols VALUES ('Suzano Papel e Celulose', 'SUZB3', 'pulp and paper', 'Salvador');
INSERT INTO stocks.stock_symbols VALUES ('Taesa S.A.', 'TAEE11', 'electricity utility', 'Rio de Janeiro');
INSERT INTO stocks.stock_symbols VALUES ('Telefônica Vivo', 'VIVT4', 'telecommunications', 'São Paulo');
INSERT INTO stocks.stock_symbols VALUES ('TIM Participações', 'TIMP3', 'telecommunications', 'Rio de Janeiro');
INSERT INTO stocks.stock_symbols VALUES ('TOTVS', 'TOTS3', 'software', 'São Paulo');
INSERT INTO stocks.stock_symbols VALUES ('Ultrapar', 'UGPA3', 'conglomerate', 'São Paulo');
INSERT INTO stocks.stock_symbols VALUES ('Usiminas', 'USIM5', 'siderurgy and metallurgy', 'Belo Horizonte');
INSERT INTO stocks.stock_symbols VALUES ('Vale', 'VALE3', 'mining', 'Rio de Janeiro');
INSERT INTO stocks.stock_symbols VALUES ('Via Varejo', 'VVAR3', 'retail', 'São Caetano do Sul');
INSERT INTO stocks.stock_symbols VALUES ('YDUQS', 'YDUQ3', 'higher education', 'Rio de Janeiro');
INSERT INTO stocks.stock_symbols VALUES ('WEG', 'WEGE3', 'industrial engineering', 'Jaraguá do Sul');

UPDATE stocks.stock_symbols SET symbol = symbol||'.SA';
