SELECT "Date"::TIMESTAMP as "ts", 'CVCB3.SA' as "symbol", "Open" as "open", "High" as "high", "Low" as "low", "Close" as "close", "Volume" as "volume" FROM "stocks"."stock_data_cvcbsa" WHERE "Volume" > 0 AND "Close" > 0 AND "Date" > (select COALESCE(MAX(ts), '1990-01-01') from "stocks"."daily_prices" where symbol = 'CVCB3.SA');

SELECT slice_time as ts, symbol, CASE WHEN slice_time <= '2020-08-07 00:00:00' THEN ROUND(TS_FIRST_VALUE("open", 'linear'), 2) WHEN slice_time < '2020-08-10' THEN ROUND(TS_LAST_VALUE("open"), 2) ELSE Null END as "open", CASE WHEN slice_time <= '2020-08-07 00:00:00' THEN ROUND(TS_FIRST_VALUE("close", 'linear'), 2) WHEN slice_time < '2020-08-10' THEN ROUND(TS_LAST_VALUE("close"), 2) ELSE Null END as "close", CASE WHEN slice_time <= '2020-08-07 00:00:00' THEN ROUND(TS_FIRST_VALUE("high", 'linear'), 2) WHEN slice_time < '2020-08-10' THEN ROUND(TS_LAST_VALUE("high"), 2) ELSE Null END as "high", CASE WHEN slice_time <= '2020-08-07 00:00:00' THEN ROUND(TS_FIRST_VALUE("low", 'linear'), 2) WHEN slice_time < '2020-08-10' THEN ROUND(TS_LAST_VALUE("low"), 2) ELSE Null END as "low", CASE WHEN slice_time <= '2020-08-07 00:00:00' THEN ROUND(TS_FIRST_VALUE("volume", 'linear'), 2) WHEN slice_time < '2020-08-10' THEN ROUND(TS_LAST_VALUE("volume"), 2) ELSE Null END as "volume" FROM ( (SELECT ts, symbol, "open", "close", "high", "low", "volume" FROM "stocks"."daily_prices" WHERE symbol = 'CVCB3.SA' and close is not null) UNION ALL (SELECT '2020-08-14'::TIMESTAMP as ts, 'CVCB3.SA' as symbol, Null as "open", Null as "close", Null as "high", Null as "low", Null as "volume") ) "input_table" TIMESERIES slice_time AS '1 day' OVER(PARTITION by symbol ORDER BY ts);


SELECT
     "ts",
     "symbol",
     "close",
     "open",
     "high",
     "low",
     "volume",
     "LAG_open_sma_1W",
     "LAG_open_sma_1M",
     "LAG_open_sma_3M",
     "LAG_open_sma_6M",
     "LAG_open_sma_1Y",
     "LAG_open_short_ema",
     "LAG_open_long_ema",
     "LAG_open_vlong_ema",
     "LAG_close_sma_1W",
     "LAG_close_sma_1M",
     "LAG_close_sma_3M",
     "LAG_close_sma_6M",
     "LAG_close_sma_1Y",
     "LAG_close_short_ema",
     "LAG_close_long_ema",
     "LAG_close_vlong_ema",
     "LAG_high_sma_1W",
     "LAG_high_sma_1M",
     "LAG_high_sma_3M",
     "LAG_high_sma_6M",
     "LAG_high_sma_1Y",
     "LAG_high_short_ema",
     "LAG_high_long_ema",
     "LAG_high_vlong_ema",
     "LAG_low_sma_1W",
     "LAG_low_sma_1M",
     "LAG_low_sma_3M",
     "LAG_low_sma_6M",
     "LAG_low_sma_1Y",
     "LAG_low_short_ema",
     "LAG_low_long_ema",
     "LAG_low_vlong_ema",
     "LAG_volume_sma_1W",
     "LAG_volume_sma_1M",
     "LAG_volume_sma_3M",
     "LAG_volume_sma_6M",
     "LAG_volume_sma_1Y",
     "LAG_volume_short_ema",
     "LAG_volume_long_ema",
     "LAG_volume_vlong_ema" 
   FROM
 (
   SELECT
     "low",
     "open",
     "close",
     "volume",
     "high",
     "ts",
     "symbol",
     "open_sma_1W",
     "open_sma_1M",
     "open_sma_3M",
     "open_sma_6M",
     "open_sma_9M",
     "open_sma_1Y",
     "open_short_ema",
     "open_long_ema",
     "open_vlong_ema",
     "close_sma_1W",
     "close_sma_1M",
     "close_sma_3M",
     "close_sma_6M",
     "close_sma_9M",
     "close_sma_1Y",
     "close_short_ema",
     "close_long_ema",
     "close_vlong_ema",
     "high_sma_1W",
     "high_sma_1M",
     "high_sma_3M",
     "high_sma_6M",
     "high_sma_9M",
     "high_sma_1Y",
     "high_short_ema",
     "high_long_ema",
     "high_vlong_ema",
     "low_sma_1W",
     "low_sma_1M",
     "low_sma_3M",
     "low_sma_6M",
     "low_sma_9M",
     "low_sma_1Y",
     "low_short_ema",
     "low_long_ema",
     "low_vlong_ema",
     "volume_sma_1W",
     "volume_sma_1M",
     "volume_sma_3M",
     "volume_sma_6M",
     "volume_sma_9M",
     "volume_sma_1Y",
     "volume_short_ema",
     "volume_long_ema",
     "volume_vlong_ema",
     LAG(open_sma_1W, 1, 0) OVER(PARTITION BY symbol ORDER BY ts) AS "LAG_open_sma_1W",
     LAG(open_sma_1M, 1, 0) OVER(PARTITION BY symbol ORDER BY ts) AS "LAG_open_sma_1M",
     LAG(open_sma_3M, 1, 0) OVER(PARTITION BY symbol ORDER BY ts) AS "LAG_open_sma_3M",
     LAG(open_sma_6M, 1, 0) OVER(PARTITION BY symbol ORDER BY ts) AS "LAG_open_sma_6M",
     LAG(open_sma_1Y, 1, 0) OVER(PARTITION BY symbol ORDER BY ts) AS "LAG_open_sma_1Y",
     LAG(open_short_ema, 1, Null) OVER(PARTITION BY symbol ORDER BY ts) AS "LAG_open_short_ema",
     LAG(open_long_ema, 1, Null) OVER(PARTITION BY symbol ORDER BY ts) AS "LAG_open_long_ema",
     LAG(open_vlong_ema, 1, Null) OVER(PARTITION BY symbol ORDER BY ts) AS "LAG_open_vlong_ema",
     LAG(close_sma_1W, 1, 0) OVER(PARTITION BY symbol ORDER BY ts) AS "LAG_close_sma_1W",
     LAG(close_sma_1M, 1, 0) OVER(PARTITION BY symbol ORDER BY ts) AS "LAG_close_sma_1M",
     LAG(close_sma_3M, 1, 0) OVER(PARTITION BY symbol ORDER BY ts) AS "LAG_close_sma_3M",
     LAG(close_sma_6M, 1, 0) OVER(PARTITION BY symbol ORDER BY ts) AS "LAG_close_sma_6M",
     LAG(close_sma_1Y, 1, 0) OVER(PARTITION BY symbol ORDER BY ts) AS "LAG_close_sma_1Y",
     LAG(close_short_ema, 1, Null) OVER(PARTITION BY symbol ORDER BY ts) AS "LAG_close_short_ema",
     LAG(close_long_ema, 1, Null) OVER(PARTITION BY symbol ORDER BY ts) AS "LAG_close_long_ema",
     LAG(close_vlong_ema, 1, Null) OVER(PARTITION BY symbol ORDER BY ts) AS "LAG_close_vlong_ema",
     LAG(high_sma_1W, 1, 0) OVER(PARTITION BY symbol ORDER BY ts) AS "LAG_high_sma_1W",
     LAG(high_sma_1M, 1, 0) OVER(PARTITION BY symbol ORDER BY ts) AS "LAG_high_sma_1M",
     LAG(high_sma_3M, 1, 0) OVER(PARTITION BY symbol ORDER BY ts) AS "LAG_high_sma_3M",
     LAG(high_sma_6M, 1, 0) OVER(PARTITION BY symbol ORDER BY ts) AS "LAG_high_sma_6M",
     LAG(high_sma_1Y, 1, 0) OVER(PARTITION BY symbol ORDER BY ts) AS "LAG_high_sma_1Y",
     LAG(high_short_ema, 1, Null) OVER(PARTITION BY symbol ORDER BY ts) AS "LAG_high_short_ema",
     LAG(high_long_ema, 1, Null) OVER(PARTITION BY symbol ORDER BY ts) AS "LAG_high_long_ema",
     LAG(high_vlong_ema, 1, Null) OVER(PARTITION BY symbol ORDER BY ts) AS "LAG_high_vlong_ema",
     LAG(low_sma_1W, 1, 0) OVER(PARTITION BY symbol ORDER BY ts) AS "LAG_low_sma_1W",
     LAG(low_sma_1M, 1, 0) OVER(PARTITION BY symbol ORDER BY ts) AS "LAG_low_sma_1M",
     LAG(low_sma_3M, 1, 0) OVER(PARTITION BY symbol ORDER BY ts) AS "LAG_low_sma_3M",
     LAG(low_sma_6M, 1, 0) OVER(PARTITION BY symbol ORDER BY ts) AS "LAG_low_sma_6M",
     LAG(low_sma_1Y, 1, 0) OVER(PARTITION BY symbol ORDER BY ts) AS "LAG_low_sma_1Y",
     LAG(low_short_ema, 1, Null) OVER(PARTITION BY symbol ORDER BY ts) AS "LAG_low_short_ema",
     LAG(low_long_ema, 1, Null) OVER(PARTITION BY symbol ORDER BY ts) AS "LAG_low_long_ema",
     LAG(low_vlong_ema, 1, Null) OVER(PARTITION BY symbol ORDER BY ts) AS "LAG_low_vlong_ema",
     LAG(volume_sma_1W, 1, 0) OVER(PARTITION BY symbol ORDER BY ts) AS "LAG_volume_sma_1W",
     LAG(volume_sma_1M, 1, 0) OVER(PARTITION BY symbol ORDER BY ts) AS "LAG_volume_sma_1M",
     LAG(volume_sma_3M, 1, 0) OVER(PARTITION BY symbol ORDER BY ts) AS "LAG_volume_sma_3M",
     LAG(volume_sma_6M, 1, 0) OVER(PARTITION BY symbol ORDER BY ts) AS "LAG_volume_sma_6M",
     LAG(volume_sma_1Y, 1, 0) OVER(PARTITION BY symbol ORDER BY ts) AS "LAG_volume_sma_1Y",
     LAG(volume_short_ema, 1, Null) OVER(PARTITION BY symbol ORDER BY ts) AS "LAG_volume_short_ema",
     LAG(volume_long_ema, 1, Null) OVER(PARTITION BY symbol ORDER BY ts) AS "LAG_volume_long_ema",
     LAG(volume_vlong_ema, 1, Null) OVER(PARTITION BY symbol ORDER BY ts) AS "LAG_volume_vlong_ema" 
   FROM
 (
   SELECT
     "low",
     "open",
     "close",
     "volume",
     "high",
     "ts",
     "symbol",
     AVG(open) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '1 week' PRECEDING AND CURRENT ROW) AS "open_sma_1W",
     AVG(open) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '1 month' PRECEDING AND CURRENT ROW) AS "open_sma_1M",
     AVG(open) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '3 month' PRECEDING AND CURRENT ROW) AS "open_sma_3M",
     AVG(open) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '6 month' PRECEDING AND CURRENT ROW) AS "open_sma_6M",
     AVG(open) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '9 month' PRECEDING AND CURRENT ROW) AS "open_sma_9M",
     AVG(open) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '1 year' PRECEDING AND CURRENT ROW) AS "open_sma_1Y",
     EXPONENTIAL_MOVING_AVERAGE(open, 0.15) OVER (PARTITION BY symbol ORDER BY ts) AS "open_short_ema",
     EXPONENTIAL_MOVING_AVERAGE(open, 0.075) OVER (PARTITION BY symbol ORDER BY ts) AS "open_long_ema",
     EXPONENTIAL_MOVING_AVERAGE(open, 0.0375) OVER (PARTITION BY symbol ORDER BY ts) AS "open_vlong_ema",
     AVG(close) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '1 week' PRECEDING AND CURRENT ROW) AS "close_sma_1W",
     AVG(close) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '1 month' PRECEDING AND CURRENT ROW) AS "close_sma_1M",
     AVG(close) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '3 month' PRECEDING AND CURRENT ROW) AS "close_sma_3M",
     AVG(close) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '6 month' PRECEDING AND CURRENT ROW) AS "close_sma_6M",
     AVG(close) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '9 month' PRECEDING AND CURRENT ROW) AS "close_sma_9M",
     AVG(close) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '1 year' PRECEDING AND CURRENT ROW) AS "close_sma_1Y",
     EXPONENTIAL_MOVING_AVERAGE(close, 0.15) OVER (PARTITION BY symbol ORDER BY ts) AS "close_short_ema",
     EXPONENTIAL_MOVING_AVERAGE(close, 0.075) OVER (PARTITION BY symbol ORDER BY ts) AS "close_long_ema",
     EXPONENTIAL_MOVING_AVERAGE(close, 0.0375) OVER (PARTITION BY symbol ORDER BY ts) AS "close_vlong_ema",
     AVG(high) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '1 week' PRECEDING AND CURRENT ROW) AS "high_sma_1W",
     AVG(high) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '1 month' PRECEDING AND CURRENT ROW) AS "high_sma_1M",
     AVG(high) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '3 month' PRECEDING AND CURRENT ROW) AS "high_sma_3M",
     AVG(high) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '6 month' PRECEDING AND CURRENT ROW) AS "high_sma_6M",
     AVG(high) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '9 month' PRECEDING AND CURRENT ROW) AS "high_sma_9M",
     AVG(high) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '1 year' PRECEDING AND CURRENT ROW) AS "high_sma_1Y",
     EXPONENTIAL_MOVING_AVERAGE(high, 0.15) OVER (PARTITION BY symbol ORDER BY ts) AS "high_short_ema",
     EXPONENTIAL_MOVING_AVERAGE(high, 0.075) OVER (PARTITION BY symbol ORDER BY ts) AS "high_long_ema",
     EXPONENTIAL_MOVING_AVERAGE(high, 0.0375) OVER (PARTITION BY symbol ORDER BY ts) AS "high_vlong_ema",
     AVG(low) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '1 week' PRECEDING AND CURRENT ROW) AS "low_sma_1W",
     AVG(low) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '1 month' PRECEDING AND CURRENT ROW) AS "low_sma_1M",
     AVG(low) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '3 month' PRECEDING AND CURRENT ROW) AS "low_sma_3M",
     AVG(low) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '6 month' PRECEDING AND CURRENT ROW) AS "low_sma_6M",
     AVG(low) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '9 month' PRECEDING AND CURRENT ROW) AS "low_sma_9M",
     AVG(low) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '1 year' PRECEDING AND CURRENT ROW) AS "low_sma_1Y",
     EXPONENTIAL_MOVING_AVERAGE(low, 0.15) OVER (PARTITION BY symbol ORDER BY ts) AS "low_short_ema",
     EXPONENTIAL_MOVING_AVERAGE(low, 0.075) OVER (PARTITION BY symbol ORDER BY ts) AS "low_long_ema",
     EXPONENTIAL_MOVING_AVERAGE(low, 0.0375) OVER (PARTITION BY symbol ORDER BY ts) AS "low_vlong_ema",
     AVG(volume) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '1 week' PRECEDING AND CURRENT ROW) AS "volume_sma_1W",
     AVG(volume) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '1 month' PRECEDING AND CURRENT ROW) AS "volume_sma_1M",
     AVG(volume) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '3 month' PRECEDING AND CURRENT ROW) AS "volume_sma_3M",
     AVG(volume) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '6 month' PRECEDING AND CURRENT ROW) AS "volume_sma_6M",
     AVG(volume) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '9 month' PRECEDING AND CURRENT ROW) AS "volume_sma_9M",
     AVG(volume) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '1 year' PRECEDING AND CURRENT ROW) AS "volume_sma_1Y",
     EXPONENTIAL_MOVING_AVERAGE(volume, 0.15) OVER (PARTITION BY symbol ORDER BY ts) AS "volume_short_ema",
     EXPONENTIAL_MOVING_AVERAGE(volume, 0.075) OVER (PARTITION BY symbol ORDER BY ts) AS "volume_long_ema",
     EXPONENTIAL_MOVING_AVERAGE(volume, 0.0375) OVER (PARTITION BY symbol ORDER BY ts) AS "volume_vlong_ema" 
   FROM
 (
   SELECT
     "low",
     "open",
     "close",
     "volume",
     "high",
     "ts",
     "symbol" 
   FROM
 "stocks"."daily_prices") 
VERTICAPY_SUBTABLE ORDER BY "ts" DESC) 
VERTICAPY_SUBTABLE) 
VERTICAPY_SUBTABLE;


SELECT * FROM (SELECT * FROM (SELECT "low", "open", "close", "volume", "high", "ts", "symbol", "real_close", "predicted_close", "close_D1_0", "close_D1_1", "roc", "roc_long_ema", "TP", "TP_DEV", "TP_MA", "BOLU", "BOLD", "_up", "_dn", "_upavg_1M", "_dnavg_1M", ROUND(100 * ( _upavg_1M / ( _upavg_1M - _dnavg_1M )), 2) AS "RMI_1M" FROM (SELECT "low", "open", "close", "volume", "high", "ts", "symbol", "real_close", "predicted_close", "close_D1_0", "close_D1_1", "roc", ROUND(EXPONENTIAL_MOVING_AVERAGE(roc, 0.075) OVER (PARTITION BY symbol ORDER BY ts), 2) AS "roc_long_ema", "TP", "TP_DEV", "TP_MA", ROUND(TP_MA + (2 * TP_DEV), 2) AS "BOLU", ROUND(TP_MA - (2 * TP_DEV), 2) AS "BOLD", "_up", "_dn", AVG(_up) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '1 month' PRECEDING AND CURRENT ROW) AS "_upavg_1M", AVG(_dn) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '1 month' PRECEDING AND CURRENT ROW) AS "_dnavg_1M" FROM (SELECT "low", "open", "close", "volume", "high", "ts", "symbol", "real_close", "predicted_close", "close_D1_0", "close_D1_1", (close - close_D1_0 ) / close_D1_1 * 100 AS "roc", "TP", STDDEV(TP) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '20 days' PRECEDING AND CURRENT ROW) AS "TP_DEV", AVG(TP) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '20 days' PRECEDING AND CURRENT ROW) AS "TP_MA", CASE WHEN close > close_D1_0 THEN close - close_D1_0 ELSE 0 END AS "_up", CASE WHEN close > close_D1_0 THEN 0 ELSE close_D1_0 - close END AS "_dn" FROM (SELECT "low", "open", "close", "volume", "high", "ts", "symbol", CASE WHEN ts <= '2020-08-07 00:00:00' THEN ROUND(close, 2) ELSE Null END AS "real_close", CASE WHEN ts >= '2020-08-07 00:00:00' THEN ROUND(close, 2) ELSE Null END AS "predicted_close", LAG(close, 1, 0) OVER(PARTITION BY symbol ORDER BY ts) AS "close_D1_0", LAG(close, 1, 1) OVER(PARTITION BY symbol ORDER BY ts) AS "close_D1_1", apply_avg(ARRAY[ high, low, close ]) AS "TP" FROM (SELECT "low", "open", "close", "volume", "high", "ts", "symbol" FROM "stocks"."daily_prices") VERTICAPY_SUBTABLE) VERTICAPY_SUBTABLE) VERTICAPY_SUBTABLE) VERTICAPY_SUBTABLE) VERTICAPY_SUBTABLE WHERE (ts >= ADD_MONTHS(CURRENT_TIMESTAMP, -6)) ORDER BY "ts" DESC) VERTICAPY_SUBTABLE;

SELECT COUNT(*) FROM (SELECT * FROM (SELECT "low", "open", "close", "volume", "high", "ts", "symbol", "real_close", "predicted_close", "close_D1_0", "close_D1_1", "roc", "roc_long_ema", "TP", "TP_DEV", "TP_MA", "BOLU", "BOLD", "_up", "_dn", "_upavg_1M", "_dnavg_1M", ROUND(100 * ( _upavg_1M / ( _upavg_1M - _dnavg_1M )), 2) AS "RMI_1M" FROM (SELECT "low", "open", "close", "volume", "high", "ts", "symbol", "real_close", "predicted_close", "close_D1_0", "close_D1_1", "roc", ROUND(EXPONENTIAL_MOVING_AVERAGE(roc, 0.075) OVER (PARTITION BY symbol ORDER BY ts), 2) AS "roc_long_ema", "TP", "TP_DEV", "TP_MA", ROUND(TP_MA + (2 * TP_DEV), 2) AS "BOLU", ROUND(TP_MA - (2 * TP_DEV), 2) AS "BOLD", "_up", "_dn", AVG(_up) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '1 month' PRECEDING AND CURRENT ROW) AS "_upavg_1M", AVG(_dn) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '1 month' PRECEDING AND CURRENT ROW) AS "_dnavg_1M" FROM (SELECT "low", "open", "close", "volume", "high", "ts", "symbol", "real_close", "predicted_close", "close_D1_0", "close_D1_1", (close - close_D1_0 ) / close_D1_1 * 100 AS "roc", "TP", STDDEV(TP) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '20 days' PRECEDING AND CURRENT ROW) AS "TP_DEV", AVG(TP) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '20 days' PRECEDING AND CURRENT ROW) AS "TP_MA", CASE WHEN close > close_D1_0 THEN close - close_D1_0 ELSE 0 END AS "_up", CASE WHEN close > close_D1_0 THEN 0 ELSE close_D1_0 - close END AS "_dn" FROM (SELECT "low", "open", "close", "volume", "high", "ts", "symbol", CASE WHEN ts <= '2020-08-07 00:00:00' THEN ROUND(close, 2) ELSE Null END AS "real_close", CASE WHEN ts >= '2020-08-07 00:00:00' THEN ROUND(close, 2) ELSE Null END AS "predicted_close", LAG(close, 1, 0) OVER(PARTITION BY symbol ORDER BY ts) AS "close_D1_0", LAG(close, 1, 1) OVER(PARTITION BY symbol ORDER BY ts) AS "close_D1_1", apply_avg(ARRAY[ high, low, close ]) AS "TP" FROM (SELECT "low", "open", "close", "volume", "high", "ts", "symbol" FROM "stocks"."daily_prices") VERTICAPY_SUBTABLE) VERTICAPY_SUBTABLE) VERTICAPY_SUBTABLE) VERTICAPY_SUBTABLE) VERTICAPY_SUBTABLE WHERE (ts >= ADD_MONTHS(CURRENT_TIMESTAMP, -6))) VERTICAPY_SUBTABLE;

SELECT COUNT(*) FROM (SELECT "low", "open", "close", "volume", "high", "ts", "symbol", "real_close", "predicted_close", "close_D1_0", "close_D1_1", "roc", "roc_long_ema", "TP", "TP_DEV", "TP_MA", "BOLU", "BOLD", "_up", "_dn", "_upavg_1M", "_dnavg_1M", ROUND(100 * ( _upavg_1M / ( _upavg_1M - _dnavg_1M )), 2) AS "RMI_1M" FROM (SELECT "low", "open", "close", "volume", "high", "ts", "symbol", "real_close", "predicted_close", "close_D1_0", "close_D1_1", "roc", ROUND(EXPONENTIAL_MOVING_AVERAGE(roc, 0.075) OVER (PARTITION BY symbol ORDER BY ts), 2) AS "roc_long_ema", "TP", "TP_DEV", "TP_MA", ROUND(TP_MA + (2 * TP_DEV), 2) AS "BOLU", ROUND(TP_MA - (2 * TP_DEV), 2) AS "BOLD", "_up", "_dn", AVG(_up) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '1 month' PRECEDING AND CURRENT ROW) AS "_upavg_1M", AVG(_dn) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '1 month' PRECEDING AND CURRENT ROW) AS "_dnavg_1M" FROM (SELECT "low", "open", "close", "volume", "high", "ts", "symbol", "real_close", "predicted_close", "close_D1_0", "close_D1_1", (close - close_D1_0 ) / close_D1_1 * 100 AS "roc", "TP", STDDEV(TP) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '20 days' PRECEDING AND CURRENT ROW) AS "TP_DEV", AVG(TP) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '20 days' PRECEDING AND CURRENT ROW) AS "TP_MA", CASE WHEN close > close_D1_0 THEN close - close_D1_0 ELSE 0 END AS "_up", CASE WHEN close > close_D1_0 THEN 0 ELSE close_D1_0 - close END AS "_dn" FROM (SELECT "low", "open", "close", "volume", "high", "ts", "symbol", CASE WHEN ts <= '2020-08-07 00:00:00' THEN ROUND(close, 2) ELSE Null END AS "real_close", CASE WHEN ts >= '2020-08-07 00:00:00' THEN ROUND(close, 2) ELSE Null END AS "predicted_close", LAG(close, 1, 0) OVER(PARTITION BY symbol ORDER BY ts) AS "close_D1_0", LAG(close, 1, 1) OVER(PARTITION BY symbol ORDER BY ts) AS "close_D1_1", apply_avg(ARRAY[ high, low, close ]) AS "TP" FROM (SELECT "low", "open", "close", "volume", "high", "ts", "symbol" FROM "stocks"."daily_prices") VERTICAPY_SUBTABLE) VERTICAPY_SUBTABLE) VERTICAPY_SUBTABLE) VERTICAPY_SUBTABLE) VERTICAPY_SUBTABLE;

SELECT round((100::float * (VERTICAPY_SUBTABLE._upavg_1M / (VERTICAPY_SUBTABLE._upavg_1M - VERTICAPY_SUBTABLE._dnavg_1M))), 2) AS RMI_1M FROM (SELECT VERTICAPY_SUBTABLE.low, VERTICAPY_SUBTABLE.open, VERTICAPY_SUBTABLE.close, VERTICAPY_SUBTABLE.volume, VERTICAPY_SUBTABLE.high, VERTICAPY_SUBTABLE.ts, VERTICAPY_SUBTABLE.symbol, VERTICAPY_SUBTABLE.real_close, VERTICAPY_SUBTABLE.predicted_close, VERTICAPY_SUBTABLE.close_D1_0, VERTICAPY_SUBTABLE.close_D1_1, VERTICAPY_SUBTABLE.roc, round(exponential_moving_average(VERTICAPY_SUBTABLE.roc, 0.075::float) OVER (PARTITION BY VERTICAPY_SUBTABLE.symbol ORDER BY VERTICAPY_SUBTABLE.ts), 2) AS roc_long_ema, VERTICAPY_SUBTABLE.TP, VERTICAPY_SUBTABLE.TP_DEV, VERTICAPY_SUBTABLE.TP_MA, round((VERTICAPY_SUBTABLE.TP_MA + (2::float * VERTICAPY_SUBTABLE.TP_DEV)), 2) AS BOLU, round((VERTICAPY_SUBTABLE.TP_MA - (2::float * VERTICAPY_SUBTABLE.TP_DEV)), 2) AS BOLD, VERTICAPY_SUBTABLE._up, VERTICAPY_SUBTABLE._dn, avg(VERTICAPY_SUBTABLE._up) OVER (PARTITION BY VERTICAPY_SUBTABLE.symbol ORDER BY VERTICAPY_SUBTABLE.ts RANGE BETWEEN '30'::interval PRECEDING AND CURRENT ROW) AS _upavg_1M, avg(VERTICAPY_SUBTABLE._dn) OVER (PARTITION BY VERTICAPY_SUBTABLE.symbol ORDER BY VERTICAPY_SUBTABLE.ts RANGE BETWEEN '30'::interval PRECEDING AND CURRENT ROW) AS _dnavg_1M FROM (SELECT VERTICAPY_SUBTABLE.low, VERTICAPY_SUBTABLE.open, VERTICAPY_SUBTABLE.close, VERTICAPY_SUBTABLE.volume, VERTICAPY_SUBTABLE.high, VERTICAPY_SUBTABLE.ts, VERTICAPY_SUBTABLE.symbol, VERTICAPY_SUBTABLE.real_close, VERTICAPY_SUBTABLE.predicted_close, VERTICAPY_SUBTABLE.close_D1_0, VERTICAPY_SUBTABLE.close_D1_1, (((VERTICAPY_SUBTABLE.close - VERTICAPY_SUBTABLE.close_D1_0) / VERTICAPY_SUBTABLE.close_D1_1) * 100::float) AS roc, VERTICAPY_SUBTABLE.TP, stddev(VERTICAPY_SUBTABLE.TP) OVER (PARTITION BY VERTICAPY_SUBTABLE.symbol ORDER BY VERTICAPY_SUBTABLE.ts RANGE BETWEEN '20'::interval PRECEDING AND CURRENT ROW) AS TP_DEV, avg(VERTICAPY_SUBTABLE.TP) OVER (PARTITION BY VERTICAPY_SUBTABLE.symbol ORDER BY VERTICAPY_SUBTABLE.ts RANGE BETWEEN '20'::interval PRECEDING AND CURRENT ROW) AS TP_MA, CASE WHEN (VERTICAPY_SUBTABLE.close > VERTICAPY_SUBTABLE.close_D1_0) THEN (VERTICAPY_SUBTABLE.close - VERTICAPY_SUBTABLE.close_D1_0) ELSE 0::float END AS _up, CASE WHEN (VERTICAPY_SUBTABLE.close > VERTICAPY_SUBTABLE.close_D1_0) THEN 0::float ELSE (VERTICAPY_SUBTABLE.close_D1_0 - VERTICAPY_SUBTABLE.close) END AS _dn FROM (SELECT VERTICAPY_SUBTABLE.low, VERTICAPY_SUBTABLE.open, VERTICAPY_SUBTABLE.close, VERTICAPY_SUBTABLE.volume, VERTICAPY_SUBTABLE.high, VERTICAPY_SUBTABLE.ts, VERTICAPY_SUBTABLE.symbol, CASE WHEN (VERTICAPY_SUBTABLE.ts <= '2020-08-07 00:00:00'::timestamp) THEN round(VERTICAPY_SUBTABLE.close, 2) ELSE NULL::float END AS real_close, CASE WHEN (VERTICAPY_SUBTABLE.ts >= '2020-08-07 00:00:00'::timestamp) THEN round(VERTICAPY_SUBTABLE.close, 2) ELSE NULL::float END AS predicted_close, lag(VERTICAPY_SUBTABLE.close, 1, 0::float) OVER (PARTITION BY VERTICAPY_SUBTABLE.symbol ORDER BY VERTICAPY_SUBTABLE.ts) AS close_D1_0, lag(VERTICAPY_SUBTABLE.close, 1, 1::float) OVER (PARTITION BY VERTICAPY_SUBTABLE.symbol ORDER BY VERTICAPY_SUBTABLE.ts) AS close_D1_1, (apply_sum_float(ARRAY[VERTICAPY_SUBTABLE.high, VERTICAPY_SUBTABLE.low, VERTICAPY_SUBTABLE.close]) / apply_count(ARRAY[VERTICAPY_SUBTABLE.high, VERTICAPY_SUBTABLE.low, VERTICAPY_SUBTABLE.close])) AS TP FROM (SELECT daily_prices.low, daily_prices.open, daily_prices.close, daily_prices.volume, daily_prices.high, daily_prices.ts, daily_prices.symbol FROM stocks.daily_prices) VERTICAPY_SUBTABLE) VERTICAPY_SUBTABLE) VERTICAPY_SUBTABLE) VERTICAPY_SUBTABLE;

SELECT ROUND(100 * ( _upavg_1M / ( _upavg_1M - _dnavg_1M )), 2) AS "RMI_1M" FROM (SELECT "low", "open", "close", "volume", "high", "ts", "symbol", "real_close", "predicted_close", "close_D1_0", "close_D1_1", "roc", ROUND(EXPONENTIAL_MOVING_AVERAGE(roc, 0.075) OVER (PARTITION BY symbol ORDER BY ts), 2) AS "roc_long_ema", "TP", "TP_DEV", "TP_MA", ROUND(TP_MA + (2 * TP_DEV), 2) AS "BOLU", ROUND(TP_MA - (2 * TP_DEV), 2) AS "BOLD", "_up", "_dn", AVG(_up) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '1 month' PRECEDING AND CURRENT ROW) AS "_upavg_1M", AVG(_dn) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '1 month' PRECEDING AND CURRENT ROW) AS "_dnavg_1M" FROM (SELECT "low", "open", "close", "volume", "high", "ts", "symbol", "real_close", "predicted_close", "close_D1_0", "close_D1_1", (close - close_D1_0 ) / close_D1_1 * 100 AS "roc", "TP", STDDEV(TP) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '20 days' PRECEDING AND CURRENT ROW) AS "TP_DEV", AVG(TP) OVER(PARTITION BY symbol ORDER BY ts RANGE BETWEEN INTERVAL '20 days' PRECEDING AND CURRENT ROW) AS "TP_MA", CASE WHEN close > close_D1_0 THEN close - close_D1_0 ELSE 0 END AS "_up", CASE WHEN close > close_D1_0 THEN 0 ELSE close_D1_0 - close END AS "_dn" FROM (SELECT "low", "open", "close", "volume", "high", "ts", "symbol", CASE WHEN ts <= '2020-08-07 00:00:00' THEN ROUND(close, 2) ELSE Null END AS "real_close", CASE WHEN ts >= '2020-08-07 00:00:00' THEN ROUND(close, 2) ELSE Null END AS "predicted_close", LAG(close, 1, 0) OVER(PARTITION BY symbol ORDER BY ts) AS "close_D1_0", LAG(close, 1, 1) OVER(PARTITION BY symbol ORDER BY ts) AS "close_D1_1", apply_avg(ARRAY[ high, low, close ]) AS "TP" FROM (SELECT "low", "open", "close", "volume", "high", "ts", "symbol" FROM "stocks"."daily_prices") VERTICAPY_SUBTABLE) VERTICAPY_SUBTABLE) VERTICAPY_SUBTABLE) VERTICAPY_SUBTABLE;